import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchCoffeeStores } from "../lib/coffee-stores";
import styles from "../styles/Home.module.css";

export interface ICoffeeStore {
  fsq_id: string;
  name: string;
  imgUrl: string;
  websiteUrl: string;
  neighbourhood: string;
  location: {
    address: string;
    address_extended: string;
    cross_street: string;
    region: string;
  };
}

interface IProps {
  coffeeStores: ICoffeeStore[];
}

const Home: NextPage<IProps> = ({ coffeeStores }) => {
  console.log(coffeeStores);

  const handleOnBannerBtnClick = () => {
    console.log("clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Hero Image"
            width={700}
            height={400}
          />
        </div>
        {coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((store) => (
                <Card
                  key={store.fsq_id}
                  name={store.name}
                  imgUrl={store.imgUrl}
                  href={"/coffee-store/" + store.fsq_id}
                />
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  // console.log(context);
  const coffeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores: coffeStores,
    }, // will be passed to the page component as props
  };
};
